### ISSUE TITLE
Collab service

### ISSUE THREAD

**Issue by TheSpaceCuber** [CS3219-AY2223S1/cs3219-project-ay2223s1-g59#28]
Tutorial [here](https://www.youtube.com/watch?v=ZKEqqIO7n-k&t=396s).

1. Matching service will return an `interviewId` to client. 
2. Client will then connect to collab service by initiating a socket io connection, and specify the `room` as the `interviewId`. Both clients will be in the same `room`.

**Comment by Herrekt** [comment]
Will need to remove excessive console logs used during troubleshooting.
